# Generated by Django 6.0 on 2025-12-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='Category_img',
            field=models.ImageField(blank=True, null=True, upload_to='Category Images'),
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='Description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
