# Generated by Django 6.0 on 2025-12-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_alter_categorydb_category_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Brand', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Short_Description', models.TextField(blank=True, null=True)),
                ('Detailed_Description', models.TextField(blank=True, null=True)),
                ('Product_img1', models.ImageField(blank=True, null=True, upload_to='Product Images')),
                ('Product_img2', models.ImageField(blank=True, null=True, upload_to='Product Images')),
                ('Product_img3', models.ImageField(blank=True, null=True, upload_to='Product Images')),
            ],
        ),
    ]
