# Generated by Django 6.0 on 2026-02-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Place', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
                ('Mobile', models.BigIntegerField(blank=True, null=True)),
                ('Total_price', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
